### PR TITLE
(fix: QSlider): slider value should start from `innerMin` instead of `min` on drag #16614

### LINKED ISSUE #16614: [QSlider] Step starts from min instead of inner min, resulting in wrong stepping if using floats
### What happened?

The slider starts at 4$, when clicking anywhere on it, you get steps always ending with .8

### What did you expect to happen?

Since `innerMin` is the actual minimum selectable value, the steps should be starting from that instead and be whole numbers

### Reproduction URL

https://codepen.io/Tofandel/pen/NWoymZm?editors=101

### How to reproduce?

1. Go to the reproduction link
2. Click anywhere on the slider
3. Notice the value is `x.8 $` and it doesn't match with any of the marker label steps
4. If you click on 3, the slider caps it to inner min and stays at `3 $`
5. If you use the keyboard arrows, then you get the correct behavior

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android, Electron

### Quasar info output

_No response_

### Relevant log output

_No response_

### Additional context

The issue seems to be coming from this function which uses `min` and `max` instead of `innerMin` and `innerMax`
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/slider/use-slider.js#L236-L250

### PR DESCRIPTION
**Pull request by Tofandel**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app

I unit tested the calculation which produces the desired result but I did not test the actual behavior in a browser, as this method is used in some other places, it should definitely be tested but I'm rather confident it should work

Fixes #16614

### CODE REVIEW

File: ui/src/components/slider/use-slider.js [hunk 1]
```diff
@@ -235,10 +235,10 @@ export default function ({ updateValue, updatePosition, getDragging, formAttrs }
 
   function convertRatioToModel (ratio) {
     const { min, max, step } = props
-    let model = min + ratio * (max - min)
+    let model = innerMin.value + (ratio - innerMinRatio.value) * (max - min)
```
Comment (pdanpdan) [inline ui/src/components/slider/use-slider.js]: Why are you doing this?

Comment (Tofandel) [reply ui/src/components/slider/use-slider.js]: The calculation will return the same result before and after, but this avoid floating point operation issues, if we have a float as min and a ratio also as float we end up with a float that is not precise enough eg 3.999999
So by using innerMin directly and subtracting it from the ratio which turns up exactly the same in arithmetic we can avoid the floating point precision issue

Maybe it's already countered by the modulo but it would need some thorough unit test cases to test

Comment (rstoenescu) [reply ui/src/components/slider/use-slider.js]: Hi, but the same happens when having a floating point value for innermin. While it is an improvement for one case, it's the exact opposite for the other. And it requires an additional subtraction operation, so this change should be reverted.

**Comment by rstoenescu** [comment]
Reversed the initial model computation as per the discussion above and merged.
Thank you for contributing!
