### PR TITLE
fix(ui/ts): Fix debounced function return type (fix: #15346)

### LINKED ISSUE #15346: Typescript signature for debounce is wrong
### What happened?

When we `debounce` function, it no longer returns the same value as the original function. However, the typescript signature states that it returns the original function. This is no longer the case.

### What did you expect to happen?

Expected
```typescript
function foo = (bar: number): number => bar * 3; // (bar: number): number
const debouncedFoo = debounce(foo, 150); // (bar: number): void
```

Actual:
```typescript
function foo = (bar: number): number => bar * 3; // (bar: number): number
const debouncedFoo = debounce(foo, 150); // (bar: number): number - wrong
```

### Reproduction URL

https://codepen.io/Buri-the-scripter/pen/MWBqYmV

### How to reproduce?

Use debounced function where original returns a value.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

TypeScript Support

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Quasar info output

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Buri**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

Fixes #15346

### CODE REVIEW

File: ui/types/utils.d.ts [hunk 1]
```diff
@@ -37,11 +37,11 @@ export function debounce<F extends (...args: any[]) => any>(
   fn: F,
   wait?: number,
   immediate?: boolean
-): F & { cancel(): void };
+): ((...args: Parameters<F>) => void) & { cancel(): void };
```
Comment (yusufkandemir) [inline ui/types/utils.d.ts]: Let's also preserve the `this` type.
```suggestion
): ((this: ThisParameterType<F>, ...args: Parameters<F>) => void) & { cancel(): void };
```

File: ui/types/utils.d.ts [hunk 2]
```diff
@@ -37,11 +37,11 @@ export function debounce<F extends (...args: any[]) => any>(
...
 
 export function frameDebounce<F extends (...args: any[]) => any>(
   fn: F,
-): F & { cancel(): void };
+): ((...args: Parameters<F>) => void) & { cancel(): void };
```
Comment (yusufkandemir) [inline ui/types/utils.d.ts]: Let's also preserve the `this` type.
```suggestion
): ((this: ThisParameterType<F>, ...args: Parameters<F>) => void) & { cancel(): void };
```

**Review by yusufkandemir — APPROVED** [review]
Thanks for contributing by reporting a bug and also submitting a PR for it 👏
I will apply a change to also preserve the `this` type and merge it. This will be available in the next `quasar` package release.
