### PR TITLE
fix(ui): fix generic usage of QTreeNode type (fix: #15351)

### LINKED ISSUE #15351: QTree not using given generic param.
### What happened?

Using QTreeView, an attempt was made to add an ID/key to the nodes being shown on the tree. Doing this requires augmenting the QTreeNode<unknown> with a different type, in this case, TreeNode.
Structure:

```ts
type TreeNode = { key: string } & QTreeNode<TreeNode>;
const nodes: TreeNode[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```
```html
<q-tree v-model:selected="selected" :nodes="nodes" dense node-key="index" />
```

### What did you expect to happen?

The nodes prop would accept the augmented type without issue, as the type had a declaration and as such should fulfill the requirement of the `QTreeNode<unknown>`.

### Reproduction URL

No repro link, see images.

### How to reproduce?

[Error statement](https://media.discordapp.net/attachments/807654245640962059/1069937693871579176/image.png)

[Type image](https://media.discordapp.net/attachments/807654245640962059/1069937742869446656/image.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

_No response_

### Quasar info output

_No response_

### Relevant log output

_No response_

### Additional context

This can be fixed by doing the following instead, however, it highlights the problem that QTreenode doesn't really use the given generic parameter.
```ts
type TreeNode = { key: string } & QTreeNode<TreeNode>;
const nodes: TreeNode[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```

### PR DESCRIPTION
**Pull request by yusufkandemir**
**What kind of change does this PR introduce?**

- Bugfix

**Does this PR introduce a breaking change?**

- Yes (type-only)

**! This breaks the previous usage, so the users should migrate to the new usage. See below for more information !**

**The PR fulfills these requirements:**

- It's submitted to the `dev` branch (or `v[X]` branch)
- When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**
Resolves #15351.

Example use case: Add `{ key: string }` to the node type.

Previous usage to achieve expected behavior (isn't an obvious solution):
```ts
type TreeNode = { key: string } & QTreeNode<TreeNode>;
const nodes: TreeNode[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```
New usage:
```ts
const nodes: QTreeNode<{ key: string }>[] = [
  {
    key: 'foo',
    label: 'bar',
    children: []
  }
];
```

### CODE REVIEW

File: ui/types/api/qtree.d.ts [hunk 1]
```diff
@@ -1,24 +1,28 @@
...
+ * @template TExtra Object type to add extra properties for the node, overrides the existing ones as well
+ */
+export type QTreeNode<TExtra = unknown> = Omit<
+  {
+    label?: string;
+    icon?: string;
+    iconColor?: string;
+    img?: string;
+    avatar?: string;
+    children?: QTreeNode<TExtra>[];
```
Comment (IlCallo) [inline ui/types/api/qtree.d.ts:101]: This implementation change will break the use case where you have children which have different properties than the parent, or am I incorrect?
Maybe we can add 2 generics, one for the children Node type (which defaults to the same type of the parent) and one for extra properties on the current node

**Comment by rstoenescu** [comment]
Haven't looked at the changes from this PR, but a few things to keep in mind:
1. The nodes can contain any property, even beyond what is required
2. There are props that can change Quasar's requirements. There may be scenarios where the props below are used so that the "standard" props can then contain whatever.
  
image

**Comment by IlCallo** [comment]
> The nodes can contain any property, even beyond what is required

Yes, this is accomplished by this last bit: `[...] & (unknown extends TExtra ? Record<string, any> : TExtra)`
If you provide the generic parameter, you get full type safety, otherwise you get to put in any kind of property

> There are props that can change Quasar's requirements. There may be scenarios where the props below are used so that the "standard" props can then contain whatever.

I think the `Omit<..., unknown extends TExtra ? "" : keyof TExtra>`, plus the previous bit, takes care of this
And the fact that all well-known properties are optional by default
If you provide a `TExtra`, you can provide your "shape" of the additional fields for your use case
We could add more generics to account for the props you highlighted, but I don't think it's worth right now

**Comment by IlCallo** [comment]
> The nodes can contain any property, even beyond what is required

Yes, this is accomplished by this last bit: `[...] & (unknown extends TExtra ? Record<string, any> : TExtra)`
If you provide the generic parameter, you get full type safety, otherwise you get to put in any kind of property

> There are props that can change Quasar's requirements. There may be scenarios where the props below are used so that the "standard" props can then contain whatever.

I think the `Omit<..., unknown extends TExtra ? "" : keyof TExtra>`, plus the previous bit, takes care of this
And the fact that all well-known properties are optional by default
If you provide a `TExtra`, you can provide your "shape" of the additional fields for your use case
We could add more generics to account for the props you highlighted, but I don't think it's worth right now

File: ui/types/api/qtree.d.ts (hunk 1 above)
Comment (yusufkandemir) [reply ui/types/api/qtree.d.ts:101]: It is possible to override the `children` type like this:
```ts
type ChildNode = QTreeNode<{ foo: string }>
type ParentNode = QTreeNode<{ bar: number; children?: ChildNode[] }>
```
Sure, we can add another generic type parameter, but I think the existing solution is simpler and more flexible. You can make the children required this way, or even use a tuple type to have a known child sequence, etc.
```ts
type ChildNode = QTreeNode<{ foo: string }>
// required children
type ParentNode = QTreeNode<{ bar: number; children: ChildNode[] }>
```
```ts
type ChildNode1 = QTreeNode<{ foo: string }>
type ChildNode2 = QTreeNode<{ baz: string }>
// required children with specific children count/order/types
type ParentNode = QTreeNode<{ bar: number; children: [ChildNode1, ChildNode2] }>
```

Comment (yusufkandemir) [reply ui/types/api/qtree.d.ts:101]: Here is an example for representing the basics of a file system:
```ts
type File = {
  path: string;
  size: number;
  lastModified: number;
}
type FileNode = QTreeNode<File & { type: "file", children?: never }>;
type DirectoryNode = QTreeNode<File & { type: "directory", children?: (FileNode | DirectoryNode)[] }>;

const directory: DirectoryNode = {
  type: "directory",
  path: "/",
  size: 0,
  lastModified: 0,
  // allows both file and directory as children
  children: [
    {
      type: "file",
      path: "/foo.txt",
      size: 100,
      lastModified: 1000,
      // does not allow children
    },
    {
      type: "directory",
      path: "/bar",
      size: 0,
      lastModified: 0,
      // empty folder - doesn't have children
    }
  ]
}
```

Comment (IlCallo) [reply ui/types/api/qtree.d.ts:101]: That's actually super smart and flexible, but not so clear
Can we add some documentation about this? Or at least add these examples in the original issue

Documentation aside, LGTM at this point

Comment (yusufkandemir) [reply ui/types/api/qtree.d.ts:101]: Another advantage is allowing children to type when using a different children key. The `children` property can be different(e.g. `nodes`), which can be modified through `children-key`. So, this solution also allows easily adding the children types with different children property names as well.

Comment (yusufkandemir) [reply ui/types/api/qtree.d.ts:101]: Added some documentation with examples in the form of JSDocs
