### PR TITLE
fix(QBreadcrumbs): fix child elements disable prop detection #13824

### LINKED ISSUE #13827: Active Colors Not Showing for Breadcrumbs
### Discussed in https://github.com/quasarframework/quasar/discussions/13824

<div type='discussions-op-text'>

<sup>Originally posted by **Cassianky** June 30, 2022</sup>
Screenshot (160)

This is a comparison of the v1 and v2 quasar documentation regarding breadcrumbs. Even though the sample code is identical, but the active colours for breadcrumb is not showing for v2 quasar documentation. I saw a similar thread that was resolved with the update offered in quasar v (link: https://github.com/quasarframework/quasar/issues/11959). But I could replicate the error in quasar v2.7.1 as well. 

I'm a beginner in quasar so I'm not sure if my usage of breadcrumbs like in the documentation/link is correct. Thanks in advance.</div>

### PR DESCRIPTION
**Pull request by pdanpdan**
Fixes #13827

### CODE REVIEW

File: ui/src/components/breadcrumbs/QBreadcrumbs.js [hunk 1]
```diff
@@ -66,6 +66,7 @@ export default createComponent({
             + (disabled !== true && middle === true ? activeClass.value : '')
 
           els++
+          console.log(disabled, disabledValues, comp.props, comp.props !== null ? comp.props.disable : 'N/A')
```
Comment (yusufkandemir) [inline ui/src/components/breadcrumbs/QBreadcrumbs.js]: Left-over from debugging.
```suggestion
```

Comment (pdanpdan) [reply ui/src/components/breadcrumbs/QBreadcrumbs.js]: :) ty
