### PR TITLE
fix(ui): add aria-label to table pagination buttons (fix: #17148)

### LINKED ISSUE #17148: Missing Labels for QTable Pagination Buttons
### What happened?

The pagination buttons that appear at the bottom of QTables do not have label attributes. This violates [WCAG Success Criterion 4.1.2: Name, Role, Value (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html). 

Screenshot of axe DevTools for Chrome on a CodePen with a basic QTable. Two 'Buttons must have discernible text' issues are detected. One of the two pagination buttons is highlighted for this issue.

### What did you expect to happen?

Pagination buttons should have a detectable label attribute of some kind like `aria-label` or `title`.

### Reproduction URL

https://codepen.io/quadbaup/full/mdgoQWQ

### How to reproduce?

1. Visit the provided link to CodePen in Firefox 125
2. Authenticate on CodePen
3. Fork the linked CodePen
2. In the forked CodePen, change the view to "Debug" mode
4. Open Web Developer Tools
5. Open the Accessibility tab
6. Set the "Check for issues" dropdown to `All Issues`
7. Note the `button` Role issues:

> Text Labels and Names
> Error
> Interactive elements must be labeled. 
> [Learn more](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#interactive_elements_must_be_labeled)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

### Quasar info output

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SamVanini**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

This PR aims to solve the violation of [[WCAG Success Criterion 4.1.2: Name, Role, Value (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html)], adding aria-label attributes to pagination button.

I translated the required labels in all the supported languages, but I am not sure about the correctness of every single one, speaking myself only Italian, English and a bit of German.  

Fixes #17148

### CODE REVIEW

File: ui/lang/en-US.js [hunk 1]
```diff
@@ -39,7 +39,11 @@ export default {
     recordsPerPage: 'Records per page:',
     allRows: 'All',
     pagination: (start, end, total) => start + '-' + end + ' of ' + total,
-    columns: 'Columns'
+    columns: 'Columns',
+    pgFirst: 'First page',
+    pgPrev: 'Previous page',
+    pgNext: 'Next page',
+    pgLast: 'Last page'
```
Comment (yusufkandemir) [inline ui/lang/en-US.js]: These can be used by QPagination as well. So, it would be better to put this as a top-level property called `pagination`, instead of putting it under `table`. That way, the `pg` prefix can be dropped due to the context, e.g. `pgFirst` -> `first`.

Comment (yusufkandemir) [reply ui/lang/en-US.js]: To make this easier, search&replace can be used like this:

image

search:
```
(    pgFirst: '.*',
    pgPrev: '.*',
    pgNext: '.*',
    pgLast: '.*')
  \}
```
replace:
```
  },
  pagination: {
$1
  }
```

after that, `pgFirst` -> `first` and such can be done with simpler search&replace runs

**Comment by yusufkandemir** [comment]
This is great, thanks! When I have time, I will implement the requested changes and merge this PR.

File: ui/lang/en-US.js (hunk 1 above)
Comment (SamVanini) [reply ui/lang/en-US.js]: I moved the labels to a separate object as suggested, so it will be easier to apply the same changes to the paginator component.

**Comment by SamVanini** [comment]
I tried to implement the requested changes to the pagination component @yusufkandemir.
If you think that it could be written in a better or cleaner way I am open to suggestions and your feedback would be very much appreciated.

Thanks in advance for the review!

File: ui/src/components/table/QTable.js
Comment (yusufkandemir) [inline ui/src/components/table/QTable.js:1]: This also needs the `ariaLabels` approach with appropriate reversing, as you did in QPagination

File: ui/lang/kur-CKB.js [hunk 2]
```diff
@@ -49,7 +49,13 @@ export default {
     recordsPerPage: 'ئەنجام بۆهەر پەڕەیەک:',
     allRows: 'هەمووی',
     pagination: (start, end, total) => start + '-' + end + ' لە ' + total,
-    columns: 'ڕیز'
+    columns: 'ڕیز',
```
Comment (yusufkandemir) [inline ui/lang/kur-CKB.js]:
```suggestion
    columns: 'ڕیز'
```

File: ui/lang/ja.js [hunk 3]
```diff
@@ -40,6 +40,12 @@ export default {
     pagination: (start, end, total) => start + '-' + end + ' ／ ' + total,
     columns: '列' // 'Columns'
   },
+  pagination: {
+    first: '最初のページ', // First page
+    prev: '前のページ', // Previous page
+    next: '次のページ', // Next page
+    last: '最後のページ' // Last page
```
Comment (yusufkandemir) [inline ui/lang/ja.js]:
```suggestion
    first: '最初のページ',
    prev: '前のページ',
    next: '次のページ',
    last: '最後のページ'
```

File: ui/lang/da.js [hunk 4]
```diff
@@ -39,7 +39,13 @@ export default {
     recordsPerPage: 'Rækker per side:',
     allRows: 'Alle',
     pagination: (start, end, total) => start + '-' + end + ' af ' + total,
-    columns: 'Kolonner'
+    columns: 'Kolonner'
```
Comment (yusufkandemir) [inline ui/lang/da.js]:
```suggestion
    columns: 'Kolonner'
```

File: ui/lang/en-US.js (hunk 1 above)
Comment (yusufkandemir) [reply ui/lang/en-US.js]: Thanks, nicely done

File: ui/src/components/table/QTable.js
Comment (yusufkandemir) [reply ui/src/components/table/QTable.js:1]: I got confused, I think icons get swapped for visuals, but the logic stays the same. I think the same applies to QPagination as well. Did you test both accordingly?

**Comment by rstoenescu** [comment]
Thanks for the awesome work!
