### PR TITLE
fix(app-vite&app-webpack): Add type for router in Pinia (fix #14061)

### LINKED ISSUE #14061: Property 'router' does not exist on type in Pinia store
### Description

image
image

### Documentation Section URL

_No response_

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

### PR DESCRIPTION
**Pull request by rashidpathiyil**
Fix #14061

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

File: app-vite/templates/store/pinia/ts/index.ts [hunk 1]
```diff
@@ -1,6 +1,17 @@
...
+/*
+ * When adding new properties to stores, you should
+ * also extend the PiniaCustomProperties interface.
+ */
+
+declare module 'pinia' {
+  export interface PiniaCustomProperties {
+    readonly router: Router;
+  }
+}
```
Comment (yusufkandemir) [inline app-vite/templates/store/pinia/ts/index.ts]:
```suggestion
/*
 * When adding new properties to stores, you should also
 * extend the `PiniaCustomProperties` interface.
 * @see https://pinia.vuejs.org/core-concepts/plugins.html#typing-new-store-properties
 */
declare module 'pinia' {
  export interface PiniaCustomProperties {
    readonly router: Router;
  }
}

```

File: app-webpack/templates/store/pinia/ts/index.ts [hunk 2]
```diff
@@ -1,5 +1,17 @@
...
+/*
+ * When adding new properties to stores, you should
+ * also extend the PiniaCustomProperties interface.
+ */
+
+declare module 'pinia' {
+  export interface PiniaCustomProperties {
+    readonly router: Router;
+  }
+}
```
Comment (yusufkandemir) [inline app-webpack/templates/store/pinia/ts/index.ts]:
```suggestion
/*
 * When adding new properties to stores, you should also
 * extend the `PiniaCustomProperties` interface.
 * @see https://pinia.vuejs.org/core-concepts/plugins.html#typing-new-store-properties
 */
declare module 'pinia' {
  export interface PiniaCustomProperties {
    readonly router: Router;
  }
}
```

**Review by yusufkandemir — APPROVED** [review]

**Comment by yusufkandemir** [comment]
Thanks for noticing this and contributing it 👏
